name: Generate Snake

on:
  schedule:
    - cron: "0 */12 * * *"   # Runs every 12 hours
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Generate Snake Animation
    steps:
      - uses: actions/checkout@v3

      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: Nabilaahmed2000
          outputs: |
            dist/snake.svg

      - name: Push Snake SVG
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions
          author_email: github-actions@github.com
          message: "Generated Snake Animation"
          add: "dist/snake.svg"
